langage: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t domak/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true domak/docker-react npm run test
